[pytest]
testpaths = tests
markers =
    unit: unit tests
    integration: integration tests
    system: system tests
    nonfunctional: non-functional tests (performance, security, reliability, usability)
    smoke: mark test as smoke test
